### ISSUE TITLE
Improvement: wire directly GPIO to Reset.

### ISSUE THREAD

**Issue by rin67630** [TOLDOTECHNIK/avrdude-gpio-autoreset#4]
Your program and the solution of Dean Mao can be simplified:
We don't need to emulate the DTR with a capacitor. 

That was a trick of Arduinos to be used with a given DTR logic. 
With GPIOs we can just wire Reset of the Arduino to the GPIO pin _directly_ and reverse the logic of autoreset: GPIO High -> Low -> High.
That is much easier and saves one capacitor.

**Comment by TOLDOTECHNIK** [comment]
Thank you for your input. Theoretically this would work.

But for these reasons, the capacitor must not be omitted.
- The reset pin on the Arduino board (5V version) is pulled high to 5V.  RPi GPIO pins only support 3.3V max.
- If someone is pressing the Arduino board's reset button, this can also damage the RPi's pin if the capacitor is removed.

You will need at least one additional voltage divider, then removing the capacitor is safe.
